<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Macro for a wheel -->
    <xacro:macro name="bogie_wheel" params="
          name 
          parent_link 
          x:='0'
          y:='0'
          z:='0' 
          y_wheel:='0'
          rpy:='0 0 0' 
          wheel_diameter:='0.3' 
          wheel_length:='0.05' 
          wheel_mass:='2.5' 
          susp_diameter:='0.1' 
          susp_length:='0.2' 
          susp_mass:='1.0' 
          spring_coeff:='4000' 
          damping_coeff:='15' 
          ">

      <!-- =========================== -->
      <!-- Computed Parameters         -->
      <!-- =========================== -->
      <!-- wheel -->
      <xacro:property name="wheel_r" value="${wheel_diameter / 2.0}"/>
      <xacro:property name="wheel_l" value="${wheel_length}"/>

      <xacro:property name="wheel_ixx" value="${1.0/12.0 * wheel_mass * (3 * wheel_r * wheel_r + wheel_l * wheel_l)}"/>
      <xacro:property name="wheel_iyy" value="${0.5 * wheel_mass * wheel_r * wheel_r}"/>
      <xacro:property name="wheel_izz" value="${wheel_ixx}"/>

      <!-- Suspension property -->
      <xacro:property name="susp_r" value="${susp_diameter/2}"/>
      <xacro:property name="susp_l" value="${susp_length}"/>

      <xacro:property name="susp_ixx" value="${1.0/12.0 * susp_mass * (3 * susp_r * susp_r + susp_l * susp_l)}"/>
      <xacro:property name="susp_iyy" value="${1.0/12.0 * susp_mass * (3 * susp_r * susp_r + susp_l * susp_l)}"/>
      <xacro:property name="susp_izz" value="${1.0/12.0 * susp_mass * (3 * susp_r * susp_r + susp_l * susp_l)}"/>
    
      <xacro:property name="susp_joint_xyz" value="${x} ${y} ${z+susp_length/2}"/>
      <xacro:property name="wheel_joint_xyz" value="${0} ${y_wheel} ${-susp_length/2}"/>
      <!-- =========================== -->
      <!-- Suspension Link             -->
      <!-- =========================== -->
      <link name="${name}_suspension_link">
        <inertial>
          <mass value="${susp_mass}"/>
          <inertia ixx="${susp_ixx}" ixy="0.0" ixz="0.0"
            iyy="${susp_iyy}" iyz="0.0"
            izz="${susp_izz}"/>
        </inertial>

        <collision name="${name}_suspension_collision">
          <origin xyz="0 0 0" rpy="0 0 0"/> <!-- Rotate cylinder to face +Y -->
          <geometry>
            <cylinder radius="${susp_r}" length="${susp_l}"/>
          </geometry>
        </collision>

        <visual name="${name}_suspension_visual">
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${susp_r}" length="${susp_l}"/>
          </geometry>
          <material name="suspension_color">
            <color rgba="0.5 0.5 0.5 1.0"/> 
            <ambient>0 0 1 1</ambient>
            <diffuse>0 0 1 1</diffuse>
          </material>
        </visual>
      </link>

      <!-- =========================== -->
      <!-- Suspension Joint            -->
      <!-- =========================== -->
      <joint name="${name}_suspension_joint" type="prismatic">
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        <parent link="${parent_link}"/>
        <child link="${name}_suspension_link"/>
        <axis xyz="0 0 -1"/> <!-- moves along -Z -->
        <limit lower="-0.1" upper="0.1" effort="500" velocity="10.0"/>
        <!--<dynamics damping="${damping_coeff}" spring_stiffness="${spring_coeff}"/>--> <!--no springs-->
      </joint>
      <!-- Gazebo: dynamics only (NO <axis> wrapper to avoid duplication) --> 
      <xacro:if value="$(arg use_gazebo)">
        <gazebo reference="${name}_suspension_joint">
        <axis>
          <dynamics>
            <damping>${damping_coeff}</damping>
            <spring_reference>0</spring_reference>
            <spring_stiffness>${spring_coeff}</spring_stiffness>
          </dynamics>
        </axis>
          <!--<axis>
            <xyz>0 0 -1</xyz>
            <limit>
              <lower>-0.07</lower>
              <upper>0.07</upper>
              <effort>100</effort>
              <velocity>10.0</velocity>
            </limit>
            <dynamics>
              <damping>${damping_coeff}</damping>
              <spring_reference>0</spring_reference>
              <spring_stiffness>${spring_coeff}</spring_stiffness>
            </dynamics>
          </axis>
          -->
        </gazebo>
      </xacro:if>
      <!-- =========================== -->
      <!-- wheel Link                  -->
      <!-- =========================== -->
      <link name="${name}_wheel_link">
        <inertial>
          <mass value="${wheel_mass}"/>
          <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0"
            iyy="${wheel_iyy}" iyz="0.0"
            izz="${wheel_izz}"/>
        </inertial>
        
        <collision name="${name}_wheel_collision">
          <origin xyz="0 0 0" rpy="1.5708 0 0"/><!-- only rotate the cylinder -->
          <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_l}"/>
          </geometry>
        </collision>

        <visual name="${name}_wheel_visual">
          <origin xyz="0 0 0" rpy="1.5708 0 0"/>
          <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_l}"/>
          </geometry>
          <material name="bogie_wheel_color">
            <color rgba="0.5 0.5 0.5 1.0"/> 
            <ambient>0 0 1 1</ambient>
            <diffuse>0 0 1 1</diffuse>
          </material>
        </visual>
      </link>

      <!-- =========================== -->
      <!-- wheel Revolute Joint        -->
      <!-- =========================== -->
      <joint name="${name}_wheel_joint" type="continuous">
        <origin xyz="${wheel_joint_xyz}" rpy="0 0 0"/> <!-- the *only* translation -->
        <parent link="${name}_suspension_link"/>
        <child link="${name}_wheel_link"/>
        <axis xyz="0 1 0"/>
      </joint>
    </xacro:macro>
</robot>