<?xml version="1.0"?>
<robot name="trackbot_vehicle" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="wheel.xacro" />
  <xacro:include filename="bogie.xacro" />
  <xacro:include filename="../trackbot_sensors/sensors.xacro" />
  <xacro:include filename="$(find trackbot_gazebo)/urdf/common_properties.urdf"/>

  <xacro:arg name="use_gazebo" default="false"/>

  <!-- Properties for main body -->
  <xacro:property name="body_length" value="1.8"/>
  <xacro:property name="body_width" value="0.96"/>
  <xacro:property name="body_height" value="0.3"/>
  <xacro:property name="body_mass" value="100.0"/>

  <!-- Properties for drive wheel -->
  <xacro:property name="drive_whl_d" value="0.3"/>
  <xacro:property name="drive_whl_w" value="0.25"/>
  <xacro:property name="drive_whl_mass" value="10.0"/>
  <xacro:property name="drive_whl_front_x" value="0.8"/>
  <xacro:property name="drive_whl_rear_x" value="-0.8"/>
  <xacro:property name="drive_whl_offset_y" value="${body_width/2+drive_whl_w/2+0.01}"/>
  <xacro:property name="drive_whl_offset_z" value="0.15"/>

  <!-- Properties for bogies -->
  <xacro:property name="bogie_whl_d" value="0.2"/>
  <xacro:property name="bogie_whl_w" value="0.2"/>
  <xacro:property name="bogie_whl_mass" value="5.0"/>
  <xacro:property name="bogie_susp_d" value="0.1"/>
  <xacro:property name="bogie_susp_l" value="0.2"/>
  <xacro:property name="bogie_1_x" value="0.5"/>  <!-- position x for bogie wheels 1, 2, 3 -->
  <xacro:property name="bogie_2_x" value="0.0"/>
  <xacro:property name="bogie_3_x" value="-0.5"/>
  <xacro:property name="bogie_y" value="${body_width/2+bogie_susp_d/2}"/>  <!-- Bogie offset in Y axis-->
  <xacro:property name="bogie_z" value="0.0"/>
  <xacro:property name="bogie_whl_left_y" value="${bogie_susp_d/2 + bogie_whl_w/2}"/>
  <xacro:property name="bogie_whl_right_y" value="${-bogie_susp_d/2 - bogie_whl_w/2}"/>
  <xacro:property name="bogie_susp_mass" value="1.0"/>
  <xacro:property name="bogie_spring_coeff" value="1000"/>
  <xacro:property name="bogie_damping_coeff" value="0.01"/>

  <!-- Properties for sensors -->
  <xacro:property name="camera_front_xyz" value="0.9 0 0.3"/>
  <xacro:property name="camera_front_rpy" value="0 0 0"/>

  <xacro:property name="lidar_front_xyz" value="0.9 0 0.4"/>
  <xacro:property name="lidar_front_rpy" value="0 0 0"/>

    <!-- Dummy root link with no inertia -->
    <link name="root"/>

    <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
    <link name="base_footprint"/>

    <!-- Base Link -->
    <link name="base_link">
      <inertial>
        <mass value="${body_mass}"/>
        <inertia ixx="${body_mass/12*(body_width*body_width+body_height*body_height)}" ixy="0.0" ixz="0.0"
                iyy="${body_mass/12*(body_length*body_length+body_height*body_height)}" iyz="0.0"
                izz="${body_mass/12*(body_length*body_length+body_width*body_width)}"/>
      </inertial>
      
      <collision name="base_collision">
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <geometry>
          <box size="${body_length} ${body_width} ${body_height}"/>
        </geometry>
      </collision>
      
      <visual name="base_visual">
        <origin xyz="0 0 0.15" rpy="0 0 0"/>
        <geometry>
          <!-- Use model:// with the *model name* that has model.config -->
          <mesh filename="package://trackbot_vehicle/meshes/robot_base.stl"
                scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="light_red">
        </material>
        <cast_shadows>true</cast_shadows>
      </visual>
    </link>

    <!-- ************************ JOINTS ***********************************  -->
    <!-- Your original root becomes a child -->
    <joint name="root_to_base" type="fixed">
      <parent link="root"/>
      <child link="base_footprint"/>
    </joint>

    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>
    <gazebo>
      <plugin name="gz::sim::systems::Sensors"
          filename="gz-sim-sensors-system">
      </plugin>
      <plugin 
        filename="gz-sim-imu-system"
        name="gz::sim::systems::Imu"> 
      </plugin>
    </gazebo>

    <!-- Instantiate sensors -->
    <xacro:camera_sensor sensor_name="front_camera" parent_link="base_link" xyz="${camera_front_xyz}" rpy="${camera_front_rpy}"/>
    <xacro:imu_sensor sensor_name="inertial_unit" parent_link="base_link"/>

    <!-- Instantiate four drive wheels -->
    <xacro:drive_wheel name="drivewhl_left_f" wheel_diameter="${drive_whl_d}" wheel_length="${drive_whl_w}" wheel_mass="${drive_whl_mass}"
        x="${drive_whl_front_x}" y="${drive_whl_offset_y}" z="${drive_whl_offset_z}"/>
    <xacro:drive_wheel name="drivewhl_right_f" wheel_diameter="${drive_whl_d}" wheel_length="${drive_whl_w}" wheel_mass="${drive_whl_mass}"
        x="${drive_whl_front_x}" y="-${drive_whl_offset_y}" z="${drive_whl_offset_z}"/>
    <xacro:drive_wheel name="drivewhl_left_r" wheel_diameter="${drive_whl_d}" wheel_length="${drive_whl_w}" wheel_mass="${drive_whl_mass}"
        x="${drive_whl_rear_x}" y="${drive_whl_offset_y}" z="${drive_whl_offset_z}"/>
    <xacro:drive_wheel name="drivewhl_right_r" wheel_diameter="${drive_whl_d}" wheel_length="${drive_whl_w}" wheel_mass="${drive_whl_mass}"
        x="${drive_whl_rear_x}" y="-${drive_whl_offset_y}" z="${drive_whl_offset_z}"/>

    <!-- Instantiate bogie wheels -->
    <xacro:bogie_wheel name="bogie_left_1" parent_link="base_link" 
        x="${bogie_1_x}" y="${bogie_y}" z="${bogie_z}" y_wheel="${bogie_whl_left_y}"
        wheel_diameter="${bogie_whl_d}" wheel_length="${bogie_whl_w}" wheel_mass="${bogie_whl_mass}" 
        susp_diameter="${bogie_susp_d}" susp_length="${bogie_susp_l}" susp_mass="${bogie_susp_mass}"
        spring_coeff="${bogie_spring_coeff}" damping_coeff="${bogie_damping_coeff}"/>

    <xacro:bogie_wheel name="bogie_left_2" parent_link="base_link" 
        x="${bogie_2_x}" y="${bogie_y}" z="${bogie_z}" y_wheel="${bogie_whl_left_y}"
        wheel_diameter="${bogie_whl_d}" wheel_length="${bogie_whl_w}" wheel_mass="${bogie_whl_mass}" 
        susp_diameter="${bogie_susp_d}" susp_length="${bogie_susp_l}" susp_mass="${bogie_susp_mass}"
        spring_coeff="${bogie_spring_coeff}" damping_coeff="${bogie_damping_coeff}"/>

    <xacro:bogie_wheel name="bogie_left_3" parent_link="base_link" 
        x="${bogie_3_x}" y="${bogie_y}" z="${bogie_z}" y_wheel="${bogie_whl_left_y}"
        wheel_diameter="${bogie_whl_d}"  wheel_length="${bogie_whl_w}" wheel_mass="${bogie_whl_mass}" 
        susp_diameter="${bogie_susp_d}" susp_length="${bogie_susp_l}" susp_mass="${bogie_susp_mass}"
        spring_coeff="${bogie_spring_coeff}" damping_coeff="${bogie_damping_coeff}"/>
    
    <xacro:bogie_wheel name="bogie_right_1" parent_link="base_link" 
        x="${bogie_1_x}" y="${-bogie_y}" z="${bogie_z}" y_wheel="${bogie_whl_right_y}"
        wheel_diameter="${bogie_whl_d}" wheel_length="${bogie_whl_w}" wheel_mass="${bogie_whl_mass}" 
        susp_diameter="${bogie_susp_d}" susp_length="${bogie_susp_l}" susp_mass="${bogie_susp_mass}"
        spring_coeff="${bogie_spring_coeff}" damping_coeff="${bogie_damping_coeff}"/>

    <xacro:bogie_wheel name="bogie_right_2" parent_link="base_link" 
        x="${bogie_2_x}" y="${-bogie_y}" z="${bogie_z}" y_wheel="${bogie_whl_right_y}"
        wheel_diameter="${bogie_whl_d}" wheel_length="${bogie_whl_w}" wheel_mass="${bogie_whl_mass}" 
        susp_diameter="${bogie_susp_d}" susp_length="${bogie_susp_l}" susp_mass="${bogie_susp_mass}"
        spring_coeff="${bogie_spring_coeff}" damping_coeff="${bogie_damping_coeff}"/>
        
    <xacro:bogie_wheel name="bogie_right_3" parent_link="base_link" 
        x="${bogie_3_x}" y="${-bogie_y}" z="${bogie_z}" y_wheel="${bogie_whl_right_y}"
        wheel_diameter="${bogie_whl_d}" wheel_length="${bogie_whl_w}" wheel_mass="${bogie_whl_mass}" 
        susp_diameter="${bogie_susp_d}" susp_length="${bogie_susp_l}" susp_mass="${bogie_susp_mass}"
        spring_coeff="${bogie_spring_coeff}" damping_coeff="${bogie_damping_coeff}"/>

    <!-- Plugin to use ROS2 DiffDrive -->
    <gazebo>
      <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">

        <!--<left_joint>drivewhl_left_f_joint</left_joint>
        <left_joint>drivewhl_left_r_joint</left_joint>
        <right_joint>drivewhl_right_f_joint</right_joint>
        <right_joint>drivewhl_right_r_joint</right_joint>-->
        <left_joint>bogie_left_1_wheel_joint</left_joint>
        <left_joint>bogie_left_2_wheel_joint</left_joint>
        <left_joint>bogie_left_3_wheel_joint</left_joint>
        <right_joint>bogie_right_1_wheel_joint</right_joint>
        <right_joint>bogie_right_2_wheel_joint</right_joint>
        <right_joint>bogie_right_3_wheel_joint</right_joint>

        <!-- kinematics -->
        <wheel_separation>${2 * drive_whl_offset_y}</wheel_separation>
        <wheel_radius>${drive_whl_d}/2</wheel_radius>

        <!-- limits -->
        <max_linear_acceleration>1.0</max_linear_acceleration>

        <topic>cmd_vel</topic>
        <odom_topic>odom</odom_topic>
        <frame_id>odom</frame_id>
        <tf_topic>/tf</tf_topic>
        <odom_publisher_frequency>30</odom_publisher_frequency>
        <child_frame_id>base_footprint</child_frame_id>
        <ros>
            <namespace>/</namespace>        <!-- put ROS topics at root -->
            <remapping>cmd_vel:=cmd_vel</remapping>
            <remapping>odom:=odom</remapping>
        </ros>
      </plugin>
    </gazebo>

    <!-- Plugin to publish joint states and broadcast TF -->
    <gazebo>
      <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
        <topic>joint_states</topic>
        <publish_frequency>50</publish_frequency>
        <update_rate>30</update_rate>
        <!--<joint_name_suffix>_joint</joint_name_suffix>-->
        <joint_name>drivewhl_left_f_joint</joint_name>
        <joint_name>drivewhl_right_f_joint</joint_name>
        <joint_name>drivewhl_left_r_joint</joint_name>
        <joint_name>drivewhl_right_r_joint</joint_name>
        <joint_name>bogie_left_1_suspension_joint</joint_name>
        <joint_name>bogie_left_2_suspension_joint</joint_name>
        <joint_name>bogie_left_3_suspension_joint</joint_name>
        <joint_name>bogie_right_1_suspension_joint</joint_name>
        <joint_name>bogie_right_2_suspension_joint</joint_name>
        <joint_name>bogie_right_3_suspension_joint</joint_name>
        <joint_name>bogie_left_1_wheel_joint</joint_name>
        <joint_name>bogie_left_2_wheel_joint</joint_name>
        <joint_name>bogie_left_3_wheel_joint</joint_name>
        <joint_name>bogie_right_1_wheel_joint</joint_name>
        <joint_name>bogie_right_2_wheel_joint</joint_name>
        <joint_name>bogie_right_3_wheel_joint</joint_name>
      </plugin>
    </gazebo>

</robot>
