<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Macro for a wheel -->
    <xacro:macro name="drive_wheel" params="
        name
        wheel_diameter:='0.5'
        wheel_length:='0.1' 
        wheel_mass:='1.0'
        x:='0' 
        y:='0' 
        z:='0'
        ">
    <xacro:property name="wheel_radius" value="${wheel_diameter/2}"/>
    <xacro:property name="wheel_width" value="${wheel_length}"/>

    <link name="${name}_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                iyy="0.1" iyz="0.0"
                izz="0.1"/>
      </inertial>

      <collision name="${name}_collision">
        <origin xyz="${x} ${y} ${z}" rpy="1.5708 0 0"/> <!-- Rotate cylinder to face +Y -->
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <visual name="${name}_visual">
        <origin xy="${x} ${y} ${z}" rpy="1.5708 0 0"/> <!-- Rotate cylinder to face +Y -->
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>
    </link>

    <joint name="${name}_joint" type="continuous">
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

</robot>