<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Macro for a wheel -->
    <xacro:macro name="drive_wheel" params="
        name
        wheel_diameter:='0.5'
        wheel_length:='0.1' 
        wheel_mass:='1.0'
        x:='0' 
        y:='0' 
        z:='0'
        ">
    <xacro:property name="wheel_r" value="${wheel_diameter/2}"/>
    <xacro:property name="wheel_w" value="${wheel_length}"/>

    <xacro:property name="wheel_ixx" value="${1.0/12.0 * wheel_mass * (3 * wheel_r * wheel_r + wheel_w * wheel_w)}"/>
    <xacro:property name="wheel_iyy" value="${0.5 * wheel_mass * wheel_r * wheel_r}"/>
    <xacro:property name="wheel_izz" value="${wheel_ixx}"/>

    <link name="${name}_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0"
                iyy="${wheel_iyy}" iyz="0.0"
                izz="${wheel_izz}"/>
      </inertial>

      <collision name="${name}_collision">
        <origin xyz="${x} ${y} ${z}" rpy="1.5708 0 0"/> <!-- Rotate cylinder to face +Y -->
        <geometry>
          <cylinder radius="${wheel_r}" length="${wheel_w}"/>
        </geometry>
      </collision>

      <visual name="${name}_visual">
        <origin xy="${x} ${y} ${z}" rpy="1.5708 0 0"/> <!-- Rotate cylinder to face +Y -->
        <geometry>
          <cylinder radius="${wheel_r}" length="${wheel_w}"/>
        </geometry>
        <material name="dark">
          <ambient>0 0 1 1</ambient>
          <diffuse>0 0 1 1</diffuse>
        </material>
      </visual>
    </link>

    <joint name="${name}_joint" type="continuous">
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

</robot>